=== WeBankPartners/wecube-platform/platform-core/src/main/resources/plugin/plugin-config-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="package" type="packageType" />
  
  <xs:complexType name="packageDependencyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="version" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="packageDependenciesType">
    <xs:sequence minOccurs="0">
            <xs:element type="packageDependencyType" name="packageDependency" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="menuType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="code" use="required"/>
        <xs:attribute type="xs:string" name="cat" use="optional"/>
        <xs:attribute type="xs:string" name="displayName" use="optional"/>
        <xs:attribute type="xs:string" name="localDisplayName" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="menusType">
    <xs:sequence minOccurs="0">
      <xs:element type="menuType" name="menu" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="attributeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="datatype" use="required"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
        <xs:attribute type="xs:string" name="refPackage" use="optional"/>
        <xs:attribute type="xs:string" name="refVersion" use="optional"/>
        <xs:attribute type="xs:string" name="refEntity" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="entityType">
    <xs:sequence>
      <xs:element type="attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="displayName" use="required"/>
    <xs:attribute type="xs:string" name="description" use="optional"/>
  </xs:complexType>
  <xs:complexType name="dataModelType">
    <xs:sequence minOccurs="0">
      <xs:element type="entityType" name="entity" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="isDynamic" default="false"/>
    <xs:attribute type="xs:string" name="path" default="/data-model"/>
    <xs:attribute type="xs:string" name="method" default="GET"/>
  </xs:complexType>
  <xs:complexType name="systemParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="defaultValue" use="optional"/>
        <xs:attribute type="xs:string" name="scopeType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="systemParametersType">
    <xs:sequence minOccurs="0">
      <xs:element type="systemParameterType" name="systemParameter" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="authorityType">
    <xs:sequence>
      <xs:element type="menuType" name="menu" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="systemRoleName" use="optional"/>
  </xs:complexType>
  <xs:complexType name="authoritiesType">
    <xs:sequence minOccurs="0">
      <xs:element type="authorityType" name="authority" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>system predefined roles</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dockerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="imageName" use="required"/>
        <xs:attribute type="xs:string" name="containerName" use="required"/>
        <xs:attribute type="xs:string" name="portBindings" use="required"/>
        <xs:attribute type="xs:string" name="volumeBindings" use="optional"/>
        <xs:attribute type="xs:string" name="envVariables" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="mysqlType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="schema" use="required"/>
        <xs:attribute type="xs:string" name="initFileName" use="required"/>
        <xs:attribute type="xs:string" name="upgradeFileName"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="s3Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bucketName" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="resourceDependenciesType">
    <xs:sequence>
      <xs:element type="dockerType" name="docker" maxOccurs="unbounded"/>
      <xs:element type="mysqlType" name="mysql" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="s3Type" name="s3" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="paramPropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="dataType" use="required"/>
        <xs:attribute type="xs:string" name="refType" use="optional"/>
        <xs:attribute type="xs:string" name="refName" use="optional"/>
        <xs:attribute type="xs:string" name="mapType" use="optional"/>
        <xs:attribute type="xs:string" name="mapExpr" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="paramObjectType">
    <xs:sequence>
      <xs:element type="paramPropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="paramObjectsType">
    <xs:sequence minOccurs="0">
      <xs:element type="paramObjectType" name="paramObject" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="inputParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="datatype" use="required"/>
        <xs:attribute type="xs:string" name="mappingType" use="optional"/>
        <xs:attribute type="xs:string" name="mappingSystemVariableName" use="optional"/>
        <xs:attribute type="xs:string" name="required" use="required"/>
        <xs:attribute type="xs:string" name="mappingEntityExpression" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="inputParametersType">
    <xs:sequence>
      <xs:element type="inputParameterType" name="parameter" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="outputParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="datatype" use="optional"/>
        <xs:attribute type="xs:string" name="mappingType" use="optional"/>
        <xs:attribute type="xs:string" name="mappingEntityExpression" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="outputParametersType">
    <xs:sequence>
      <xs:element type="outputParameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="interfaceType">
    <xs:sequence>
      <xs:element type="inputParametersType" name="inputParameters" minOccurs="0"/>
      <xs:element type="outputParametersType" name="outputParameters" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="action"/>
    <xs:attribute type="xs:string" name="path"/>
    <xs:attribute type="xs:string" name="httpMethod"/>
    <xs:attribute type="xs:string" name="isAsyncProcessing" use="optional" default="N"/>
    <xs:attribute type="xs:string" name="filterRule" use="optional" default=""/>
    <xs:attribute name="type" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="APPROVAL"/>
          <xs:enumeration value="EXECUTION"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="pluginType">
    <xs:sequence>
      <xs:element type="roleBindsType" name="roleBinds" minOccurs="0"/>
      <xs:element type="interfaceType" name="interface" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="targetPackage"/>
    <xs:attribute type="xs:string" name="targetEntity"/>
    <xs:attribute type="xs:string" name="targetEntityFilterRule"/>
    <xs:attribute type="xs:string" name="registerName"/>
  </xs:complexType>
  <xs:complexType name="pluginsType">
    <xs:sequence minOccurs="0">
      <xs:element type="pluginType" name="plugin" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="roleBindType">
    <xs:attribute type="xs:string" name="permission"/>
    <xs:attribute type="xs:string" name="roleName"/>
  </xs:complexType>
  <xs:complexType name="roleBindsType">
    <xs:sequence minOccurs="0">
      <xs:element type="roleBindType" name="roleBind" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="packageType">
    <xs:sequence>
      <xs:element type="packageDependenciesType" name="packageDependencies" minOccurs="0">
        <xs:annotation>
          <xs:documentation>1.依赖分析 - 描述运行本插件包需要的其他插件</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="menusType" name="menus" minOccurs="0">
        <xs:annotation>
          <xs:documentation>2.菜单注入 - 描述运行本插件包需要注入的菜单</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="dataModelType" name="dataModel" minOccurs="0">
        <xs:annotation>
          <xs:documentation>3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="systemParametersType" name="systemParameters" minOccurs="0">
        <xs:annotation>
          <xs:documentation>4.系统参数 - 描述运行本插件包需要的系统参数</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="authoritiesType" name="authorities" minOccurs="0">
        <xs:annotation>
          <xs:documentation>5.权限设定</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="resourceDependenciesType" name="resourceDependencies">
        <xs:annotation>
          <xs:documentation>6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等)</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      <xs:element type="paramObjectsType" name="paramObjects" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>7.对象参数列表 - 描述插件包定义的对象参数结构</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      <xs:element type="pluginsType" name="plugins" minOccurs="0">
        <xs:annotation>
          <xs:documentation>8.插件列表 - 描述插件包中单个插件的输入和输出</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="version"/>
  </xs:complexType>
</xs:schema>

=== WeBankPartners/wecube-platform/platform-core/src/test/resources/plugin/register-artifacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="artifacts" version="{{VERSION}}"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plugin-config-v2.xsd">

    <!-- 1.依赖分析 - 描述运行本插件包需要的其他插件包 -->
    <packageDependencies>
        <packageDependency name="platform" version="v2.5.0"/>
        <packageDependency name="wecmdb" version="v1.5.1"/>
    </packageDependencies>
         
    <!-- 2.菜单注入 - 描述运行本插件包需要注入的菜单 -->
    <menus>
        <menu code="IMPLEMENTATION_ARTIFACT_MANAGEMENT" cat="IMPLEMENTATION" displayName="Artifacts Management" localDisplayName="应用物料管理" >/artifacts/implementation/artifact-management</menu>
    </menus>

    <!-- 3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系 -->
    <dataModel>
    </dataModel>

    <!-- 4.系统参数 - 描述运行本插件包需要的系统参数 -->
    <systemParameters>
        <systemParameter name="UPLOAD_ENABLED" scopeType="plugins" defaultValue="true"/>
        <systemParameter name="UPLOAD_NEXUS_ENABLED" scopeType="plugins" defaultValue="true"/>
        <systemParameter name="ARTIFACTS_CITYPE_SYSTEM_DESIGN" scopeType="plugins" defaultValue="37"/>
        <systemParameter name="ARTIFACTS_CITYPE_UNIT_DESIGN" scopeType="plugins" defaultValue="39"/>
        <systemParameter name="ARTIFACTS_CITYPE_DIFF_CONFIG" scopeType="plugins" defaultValue="44"/>
        <systemParameter name="ARTIFACTS_CITYPE_DEPLOY_PACKAGE" scopeType="plugins" defaultValue="45"/>
        <systemParameter name="ARTIFACTS_ENCRYPT_VARIABLE_PREFIX" scopeType="plugins" defaultValue="!,%"/>
        <systemParameter name="ARTIFACTS_FILE_VARIABLE_PREFIX" scopeType="plugins" defaultValue="^"/>
        <systemParameter name="ARTIFACTS_DEFAULT_SPECIAL_REPLACE" scopeType="plugins" defaultValue="@,#"/>
        <systemParameter name="ARTIFACTS_DIFF_CONF_EXTENSION" scopeType="plugins" defaultValue=".*"/>
        <systemParameter name="ARTIFACTS_VARIABLE_EXPRESSION" scopeType="plugins" defaultValue=".+?"/>
        <systemParameter name="LOCAL_NEXUS_SERVER_URL" scopeType="plugins" defaultValue="http://127.0.0.1:8081"/>
        <systemParameter name="LOCAL_NEXUS_USERNAME" scopeType="plugins" defaultValue="artifacts"/>
        <systemParameter name="LOCAL_NEXUS_PASSWORD" scopeType="plugins" defaultValue="artifacts"/>
        <systemParameter name="LOCAL_NEXUS_REPOSITORY" scopeType="plugins" defaultValue="artifacts"/>
        <systemParameter name="USE_REMOTE_NEXUS_ONLY" scopeType="plugins" defaultValue="false"/>
        <systemParameter name="CMDB_ARTIFACT_PATH" scopeType="plugins" defaultValue="artifact_path"/>
        <systemParameter name="NEXUS_SERVER_URL" scopeType="plugins" defaultValue="http://127.0.0.1:18888"/>
        <systemParameter name="NEXUS_USERNAME" scopeType="plugins" defaultValue="admin"/>
        <systemParameter name="NEXUS_PASSWORD" scopeType="plugins" defaultValue="admin123"/>
        <systemParameter name="NEXUS_REPOSITORY" scopeType="plugins" defaultValue="maven-releases"/>
        <systemParameter name="NEXUS_SORT_AS_STRING" scopeType="plugins" defaultValue="false"/>
        <systemParameter name="NEXUS_CONNECTOR_PORT" scopeType="plugins" defaultValue="5000"/>
    </systemParameters>

    <!-- 5.权限设定 -->
    <authorities>
        <authority systemRoleName="SUPER_ADMIN" >
            <menu code="IMPLEMENTATION_ARTIFACT_MANAGEMENT" />
        </authority >
    </authorities>

    <!-- 6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等) -->
    <resourceDependencies>
        <docker imageName="{{REPOSITORY}}:{{VERSION}}" containerName="{{REPOSITORY}}-{{VERSION}}" portBindings="{{ALLOCATE_PORT}}:9000,{{MONITOR_PORT}}:8081,5000:8082" volumeBindings="{{BASE_MOUNT_PATH}}/artifacts/log:/var/log/artifacts_corepy,{{BASE_MOUNT_PATH}}/certs:/certs,{{BASE_MOUNT_PATH}}/nexus-data:/nexus-data,/etc/localtime:/etc/localtime"
        envVariables="ARTIFACTS_UPLOAD_ENABLED={{UPLOAD_ENABLED}},ARTIFACTS_UPLOAD_NEXUS_ENABLED={{UPLOAD_NEXUS_ENABLED}},
        ARTIFACTS_CITYPE_SYSTEM_DESIGN={{ARTIFACTS_CITYPE_SYSTEM_DESIGN}},ARTIFACTS_CITYPE_UNIT_DESIGN={{ARTIFACTS_CITYPE_UNIT_DESIGN}},
        ARTIFACTS_CITYPE_DIFF_CONFIG={{ARTIFACTS_CITYPE_DIFF_CONFIG}},ARTIFACTS_CITYPE_DEPLOY_PACKAGE={{ARTIFACTS_CITYPE_DEPLOY_PACKAGE}},
        ARTIFACTS_ENCRYPT_VARIABLE_PREFIX={{ARTIFACTS_ENCRYPT_VARIABLE_PREFIX}},ARTIFACTS_FILE_VARIABLE_PREFIX={{ARTIFACTS_FILE_VARIABLE_PREFIX}},
        ARTIFACTS_DEFAULT_SPECIAL_REPLACE={{ARTIFACTS_DEFAULT_SPECIAL_REPLACE}},
        ARTIFACTS_LOCAL_NEXUS_SERVER_URL={{LOCAL_NEXUS_SERVER_URL}},ARTIFACTS_LOCAL_NEXUS_USERNAME={{LOCAL_NEXUS_USERNAME}},
        ARTIFACTS_LOCAL_NEXUS_PASSWORD={{LOCAL_NEXUS_PASSWORD}},ARTIFACTS_LOCAL_NEXUS_REPOSITORY={{LOCAL_NEXUS_REPOSITORY}},
        ARTIFACTS_USE_REMOTE_NEXUS_ONLY={{USE_REMOTE_NEXUS_ONLY}},ARTIFACTS_CMDB_ARTIFACT_PATH={{CMDB_ARTIFACT_PATH}},
        ARTIFACTS_NEXUS_SERVER_URL={{NEXUS_SERVER_URL}},ARTIFACTS_NEXUS_USERNAME={{NEXUS_USERNAME}},
        ARTIFACTS_NEXUS_PASSWORD={{NEXUS_PASSWORD}},ARTIFACTS_NEXUS_REPOSITORY={{NEXUS_REPOSITORY}},
        WECUBE_S3_ACCESS_KEY={{S3_ACCESS_KEY}},WECUBE_S3_SECRET_KEY={{S3_SECRET_KEY}},
        ARTIFACTS_DIFF_CONF_EXTENSION={{ARTIFACTS_DIFF_CONF_EXTENSION}},ARTIFACTS_VARIABLE_EXPRESSION={{ARTIFACTS_VARIABLE_EXPRESSION}},
        WECUBE_GATEWAY_URL={{GATEWAY_URL}},WECUBE_JWT_SIGNING_KEY={{JWT_SIGNING_KEY}},ARTIFACTS_NEXUS_SORT_AS_STRING={{NEXUS_SORT_AS_STRING}},
        ARTIFACTS_LOCAL_NEXUS_CONNECTOR_PORT=5000,ARTIFACTS_NEXUS_CONNECTOR_PORT={{NEXUS_CONNECTOR_PORT}}"/>
        <s3 bucketName="wecube-artifacts"/>
    </resourceDependencies>

    <!-- 7.插件列表 - 描述插件包中单个插件的输入和输出 -->
    <plugins>
        <plugin name="package">
            <interface action="upload-image" path="/artifacts/v1/packages/from-image" httpMethod="POST" isAsyncProcessing="N" type="EXECUTION">
                <inputParameters>
                    <parameter datatype="string" mappingType="constant" required="Y">unit_design</parameter>
                    <parameter datatype="string" mappingType="constant" required="Y">image_name</parameter>
                    <parameter datatype="string" mappingType="constant" required="Y">tag</parameter>
                    <parameter datatype="string" mappingType="constant" required="N">namespace</parameter>
                    <parameter datatype="string" mappingType="constant" required="N">md5</parameter>
                    <parameter datatype="string" mappingType="constant" required="N">baseline_package</parameter>
                    <parameter datatype="string" mappingType="system_variable" mappingSystemVariableName="NEXUS_SERVER_URL" required="N">nexus_url</parameter>
                    <parameter datatype="string" mappingType="system_variable" mappingSystemVariableName="NEXUS_CONNECTOR_PORT" required="N">connector_port</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">errorCode</parameter>
                    <parameter datatype="string">errorMessage</parameter>
                    <parameter datatype="string">guid</parameter>
                    <parameter datatype="string">deploy_package_url</parameter>
                </outputParameters>
            </interface>
        </plugin>
    </plugins>
</package>

=== WeBankPartners/wecube-platform/platform-core/src/test/resources/plugin/sample-plugin-config-null-blocks.xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="service-management" version="v0.1"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plugin-config-v2.xsd">

    <!-- 1.析 - 描述运行本插件包需要的其他插件包 -->
    <packageDependencies>
    </packageDependencies>

    <!-- 2.菜单注入 - 描述运行本插件包需要注入的菜单 -->
    <menus>
    </menus>

    <!-- 3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系 -->
    <dataModel>
    </dataModel>

    <!-- 4.系统参数 - 描述运行本插件包需要的系统参数 -->
    <systemParameters>
    </systemParameters>

    <!-- 5.权限设定 -->
    <authorities>
    </authorities>

    <!-- 6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等) -->
    <resourceDependencies>
        <docker imageName="service_management" containerName="service_management" portBindings="22000:21000" volumeBindings="" envVariables="-e DATA_SOURCE_URL={%s} -e DB_USER={%s} -e DB_PWD={%s} -e CORE_ADDR={%s}"/>
    </resourceDependencies>

    <!-- 7.插件列表 - 描述插件包中单个插件的输入和输出 -->
    <plugins>
    </plugins>
</package>

=== WeBankPartners/wecube-platform/platform-core/src/test/resources/plugin/sample-plugin-config-cmdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="wecmdb" version="v0.1"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plugin-config-v2.xsd">

    <!-- 1.依赖分析 - 描述运行本插件包需要的其他插件包 -->

    <!-- 2.菜单注入 - 描述运行本插件包需要注入的菜单 -->
    <menus>
        <menu code='DESIGNING_CI_DATA_ENQUIRY' cat='DESIGNING' displayName="CI Data Enquiry">/designing/ci-data-enquiry</menu>
        <menu code='DESIGNING_CI_INTEGRATED_QUERY_EXECUTION' cat='DESIGNING' displayName="CI Integrated Enquiry">/designing/ci-integrated-query-execution</menu>
        <menu code='DESIGNING_ENUM_ENQUIRY' cat='DESIGNING' displayName="Enum Enquiry">/designing/enum-enquiry</menu>

        <menu code='DESIGNING_CI_DATA_MANAGEMENT' cat='DESIGNING' displayName="CI Data Management">/designing/ci-data-management</menu>
        <menu code='DESIGNING_CI_INTEGRATED_QUERY_MANAGEMENT' cat='DESIGNING' displayName="CI Integrated Enquiry Management">/designing/ci-integrated-query-management</menu>
        <menu code='DESIGNING_ENUM_MANAGEMENT' cat='DESIGNING' displayName="Enum Management">/designing/enum-management</menu>

        <menu code='IDC_PLANNING_DESIGN' cat='DESIGNING' displayName="IDC Planning Design">/view-management/idc-planning-design</menu>
        <menu code='IDC_RESOURCE_PLANNING' cat='DESIGNING' displayName="IDC Resource Plan">/view-management/idc-resource-planning</menu>
        <menu code='APPLICATION_ARCHITECTURE_DESIGN' cat='DESIGNING' displayName="App Architecture Design">/view-management/application-architecture-design</menu>
        <menu code='APPLICATION_DEPLOYMENT_DESIGN' cat='DESIGNING' displayName="APP Deploy Design">/view-management/application-deployment-design</menu>

        <menu code='ADMIN_CMDB_MODEL_MANAGEMENT' cat='ADMIN' displayName="CMDB Model Management">/admin/cmdb-model-management</menu>
        <menu code='ADMIN_PERMISSION_MANAGEMENT' cat='ADMIN' displayName="Permission Management">/admin/permission-management</menu>
        <menu code='ADMIN_BASE_DATA_MANAGEMENT' cat='ADMIN' displayName="Base Data Management">/admin/base-data-management</menu>
        <menu code='ADMIN_QUERY_LOG' cat='ADMIN' displayName="Log Enquiry">/admin/query-log</menu>
        <menu code='ADMIN_USER_PASSWORD_MANAGEMENT' cat='ADMIN' displayName="User Password Management">/admin/user-password-management</menu>
    </menus>

    <!-- 3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系 -->
    <dataModel isDynamic="true">
    </dataModel>

    <!-- 4.系统参数 - 描述运行本插件包需要的系统参数 -->
    <systemParameters>
        <systemParameter name="wecmdb-server-url" defaultValue='http://localhost:9080/wecmdb' scopeType="global"/>
    </systemParameters>

    <!-- 5.权限设定 -->
    <authorities>
        <authority systemRoleName="SUPER_ADMIN" >
            <menu code="DESIGNING_CI_DATA_ENQUIRY" />
            <menu code="DESIGNING_CI_INTEGRATED_QUERY_EXECUTION" />
            <menu code="DESIGNING_ENUM_ENQUIRY" />
            <menu code="DESIGNING_CI_DATA_MANAGEMENT" />
            <menu code="DESIGNING_CI_INTEGRATED_QUERY_MANAGEMENT" />
            <menu code="DESIGNING_ENUM_MANAGEMENT" />
            <menu code="IDC_PLANNING_DESIGN" />
            <menu code="IDC_RESOURCE_PLANNING" />
            <menu code="APPLICATION_ARCHITECTURE_DESIGN" />
            <menu code="APPLICATION_DEPLOYMENT_DESIGN" />
            <menu code="ADMIN_CMDB_MODEL_MANAGEMENT" />
            <menu code="ADMIN_PERMISSION_MANAGEMENT" />
            <menu code="ADMIN_BASE_DATA_MANAGEMENT" />
            <menu code="ADMIN_QUERY_LOG" />
            <menu code="ADMIN_USER_PASSWORD_MANAGEMENT" />
        </authority >
    </authorities>

    <!-- 6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等) -->
    <resourceDependencies>
        <docker imageName="wecube-plugins-wecmdb" containerName="wecube-plugins-wecmdb" portBindings="22001:8081"/>
    </resourceDependencies>

    <!-- 7.插件列表 - 描述插件包中单个插件的输入和输出 -->
    <plugins>
        <plugin id="ci-data-confirm" name="CI Data Confirmation">
            <interface action="confirm" path="/data/confirm" httpMethod='POST'>
                <inputParameters>
                    <parameter datatype="string" mappingType='context' required='Y'>entityName</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>guid</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">status</parameter>
                    <parameter datatype="string">message</parameter>
                    <parameter datatype="string">guid</parameter>
                    <parameter datatype="string">fixed_date</parameter>
                </outputParameters>
            </interface>
        </plugin>
    </plugins>
</package>
