=== WeBankPartners/wecube-platform/platform-core/src/main/resources/plugin/plugin-config-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="package" type="packageType" />
  
  <xs:complexType name="packageDependencyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="version" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="packageDependenciesType">
    <xs:sequence minOccurs="0">
            <xs:element type="packageDependencyType" name="packageDependency" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="menuType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="code" use="required"/>
        <xs:attribute type="xs:string" name="cat" use="optional"/>
        <xs:attribute type="xs:string" name="displayName" use="optional"/>
        <xs:attribute type="xs:string" name="localDisplayName" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="menusType">
    <xs:sequence minOccurs="0">
      <xs:element type="menuType" name="menu" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="attributeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="datatype" use="required"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
        <xs:attribute type="xs:string" name="refPackage" use="optional"/>
        <xs:attribute type="xs:string" name="refVersion" use="optional"/>
        <xs:attribute type="xs:string" name="refEntity" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="entityType">
    <xs:sequence>
      <xs:element type="attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="displayName" use="required"/>
    <xs:attribute type="xs:string" name="description" use="optional"/>
  </xs:complexType>
  <xs:complexType name="dataModelType">
    <xs:sequence minOccurs="0">
      <xs:element type="entityType" name="entity" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="isDynamic" default="false"/>
    <xs:attribute type="xs:string" name="path" default="/data-model"/>
    <xs:attribute type="xs:string" name="method" default="GET"/>
  </xs:complexType>
  <xs:complexType name="systemParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="defaultValue" use="optional"/>
        <xs:attribute type="xs:string" name="scopeType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="systemParametersType">
    <xs:sequence minOccurs="0">
      <xs:element type="systemParameterType" name="systemParameter" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="authorityType">
    <xs:sequence>
      <xs:element type="menuType" name="menu" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="systemRoleName" use="optional"/>
  </xs:complexType>
  <xs:complexType name="authoritiesType">
    <xs:sequence minOccurs="0">
      <xs:element type="authorityType" name="authority" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>system predefined roles</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dockerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="imageName" use="required"/>
        <xs:attribute type="xs:string" name="containerName" use="required"/>
        <xs:attribute type="xs:string" name="portBindings" use="required"/>
        <xs:attribute type="xs:string" name="volumeBindings" use="optional"/>
        <xs:attribute type="xs:string" name="envVariables" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="mysqlType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="schema" use="required"/>
        <xs:attribute type="xs:string" name="initFileName" use="required"/>
        <xs:attribute type="xs:string" name="upgradeFileName"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="s3Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bucketName" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="resourceDependenciesType">
    <xs:sequence>
      <xs:element type="dockerType" name="docker" maxOccurs="unbounded"/>
      <xs:element type="mysqlType" name="mysql" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="s3Type" name="s3" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="paramPropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="dataType" use="required"/>
        <xs:attribute type="xs:string" name="refType" use="optional"/>
        <xs:attribute type="xs:string" name="refName" use="optional"/>
        <xs:attribute type="xs:string" name="mapType" use="optional"/>
        <xs:attribute type="xs:string" name="mapExpr" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="paramObjectType">
    <xs:sequence>
      <xs:element type="paramPropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="paramObjectsType">
    <xs:sequence minOccurs="0">
      <xs:element type="paramObjectType" name="paramObject" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="inputParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="datatype" use="required"/>
        <xs:attribute type="xs:string" name="mappingType" use="optional"/>
        <xs:attribute type="xs:string" name="mappingSystemVariableName" use="optional"/>
        <xs:attribute type="xs:string" name="required" use="required"/>
        <xs:attribute type="xs:string" name="mappingEntityExpression" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="inputParametersType">
    <xs:sequence>
      <xs:element type="inputParameterType" name="parameter" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="outputParameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="datatype" use="optional"/>
        <xs:attribute type="xs:string" name="mappingType" use="optional"/>
        <xs:attribute type="xs:string" name="mappingEntityExpression" use="optional"/>
        <xs:attribute type="xs:string" name="sensitiveData" use="optional" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="outputParametersType">
    <xs:sequence>
      <xs:element type="outputParameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="interfaceType">
    <xs:sequence>
      <xs:element type="inputParametersType" name="inputParameters" minOccurs="0"/>
      <xs:element type="outputParametersType" name="outputParameters" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="action"/>
    <xs:attribute type="xs:string" name="path"/>
    <xs:attribute type="xs:string" name="httpMethod"/>
    <xs:attribute type="xs:string" name="isAsyncProcessing" use="optional" default="N"/>
    <xs:attribute type="xs:string" name="filterRule" use="optional" default=""/>
    <xs:attribute name="type" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="APPROVAL"/>
          <xs:enumeration value="EXECUTION"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="pluginType">
    <xs:sequence>
      <xs:element type="roleBindsType" name="roleBinds" minOccurs="0"/>
      <xs:element type="interfaceType" name="interface" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="targetPackage"/>
    <xs:attribute type="xs:string" name="targetEntity"/>
    <xs:attribute type="xs:string" name="targetEntityFilterRule"/>
    <xs:attribute type="xs:string" name="registerName"/>
  </xs:complexType>
  <xs:complexType name="pluginsType">
    <xs:sequence minOccurs="0">
      <xs:element type="pluginType" name="plugin" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="roleBindType">
    <xs:attribute type="xs:string" name="permission"/>
    <xs:attribute type="xs:string" name="roleName"/>
  </xs:complexType>
  <xs:complexType name="roleBindsType">
    <xs:sequence minOccurs="0">
      <xs:element type="roleBindType" name="roleBind" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="packageType">
    <xs:sequence>
      <xs:element type="packageDependenciesType" name="packageDependencies" minOccurs="0">
        <xs:annotation>
          <xs:documentation>1.依赖分析 - 描述运行本插件包需要的其他插件</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="menusType" name="menus" minOccurs="0">
        <xs:annotation>
          <xs:documentation>2.菜单注入 - 描述运行本插件包需要注入的菜单</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="dataModelType" name="dataModel" minOccurs="0">
        <xs:annotation>
          <xs:documentation>3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="systemParametersType" name="systemParameters" minOccurs="0">
        <xs:annotation>
          <xs:documentation>4.系统参数 - 描述运行本插件包需要的系统参数</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="authoritiesType" name="authorities" minOccurs="0">
        <xs:annotation>
          <xs:documentation>5.权限设定</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="resourceDependenciesType" name="resourceDependencies">
        <xs:annotation>
          <xs:documentation>6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等)</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      <xs:element type="paramObjectsType" name="paramObjects" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>7.对象参数列表 - 描述插件包定义的对象参数结构</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      <xs:element type="pluginsType" name="plugins" minOccurs="0">
        <xs:annotation>
          <xs:documentation>8.插件列表 - 描述插件包中单个插件的输入和输出</xs:documentation>
        </xs:annotation>
      </xs:element>
      
      
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="version"/>
  </xs:complexType>
</xs:schema>

=== WeBankPartners/wecube-platform/platform-core/src/test/resources/register-for-parser-test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<package name="service-management" version="v0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plugin-config-v2.xsd">

    <!-- 1.依赖分析 - 描述运行本插件包需要的其他插件包 -->
    <packageDependencies>
        <packageDependency name='xxx' version='1.0'/>
        <packageDependency name='xxx233' version='1.5'/>
    </packageDependencies>

    <!-- 2.菜单注入 - 描述运行本插件包需要注入的菜单 -->
    <menus>
        <menu code='JOBS_SERVICE_CATALOG_MANAGEMENT' cat='JOBS' displayName="Servive Catalog Management" cnDisplayName="服务类型管理">
            /service-catalog
        </menu>
        <menu code='JOBS_TASK_MANAGEMENT' cat='JOBS' displayName="Task Management" cnDisplayName="任务管理">/task-management</menu>
    </menus>

    <!-- 3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系 -->

    <dataModel isDynamic="true" path="/data-model" method="GET">
        <entity name="service_catalogue" displayName="服务目录" description="服务目录模型">
            <attribute name="id" datatype="int" description="唯一ID"/>
            <attribute name="name" datatype="str" description="名字"/>
            <attribute name="status" datatype="str" description="状态"/>
        </entity>
        <entity name="service_pipeline" displayName="服务通道" description="服务通道模型">
            <attribute name="id" datatype="int" description="唯一ID"/>
            <attribute name="service_catalogue_id" datatype='ref' description="所属服务目录"
                       refPackage="service-management" refEntity="service_catalogue" ref="id"/>
            <attribute name="name" datatype="str" description="名字"/>
            <attribute name="owner_role_id" datatype="int" description="所属角色"/> <!--应该是ref到角色ID，目前暂无-->
            <attribute name="status" datatype="str" description="状态"/>
        </entity>
        <entity name="service_request_template" displayName="服务请求模板" description="服务请求模板模型">
            <attribute name="id" datatype="int" description="唯一ID"/>
            <attribute name="service_pipeline_id" datatype='ref' description="所属服务通道"
                       refPackage="service-management" refEntity="service_pipeline" ref="id"/>
            <attribute name="name" datatype="str" description="名字"/>
            <attribute name="process_defined_key" datatype="str" description="名字"/>
            <attribute name="status" datatype="str" description="状态"/>
        </entity>
        <entity name="service_request" displayName="服务请求" description="服务请求模型">
            <attribute name="id" datatype="int" description="唯一ID"/>
            <attribute name="template_id" datatype='ref' description="所属服务模板"
                       refPackage="service-management" refEntity="service_request_template" ref="id"/>
            <attribute name="reporter" datatype="str" description="上报人"/>
            <attribute name="reporter_role_id" datatype="str" description="上报角色ID"/>
            <attribute name="report_time" datatype="timestamp" description="上报时间"/>
            <attribute name="emergency" datatype="str" description="紧急程度"/>
            <attribute name="result" datatype="str" description="结果"/>
            <attribute name="process_instance_id" datatype="str" description="流程模板ID"/>
            <attribute name="status" datatype="str" description="状态"/>
        </entity>
        <entity name="task" displayName="任务" description="任务模型">
            <attribute name="id" datatype="int" description="唯一ID"/>
            <attribute name="service_request_id" datatype='ref' description="所属服务请求"
                       refPackage="service-management" refEntity="service_request" ref="id"/>
            <attribute name="process_instance_id" datatype="str" description="流程实例ID"/>
            <attribute name="callback_url" datatype="int" description="回调url"/>
            <attribute name="name" datatype="int" description="任务名称"/>
            <attribute name="process_definition_key" datatype="int" description="流程模板ID"/>
            <attribute name="reporter" datatype="str" description="上报人"/>
            <attribute name="report_time" datatype="timestamp" description="上报时间"/>
            <attribute name="operator_role_id" datatype="str" description="操作角色ID"/>
            <attribute name="operator" datatype="str" description="操作人"/>
            <attribute name="operator_time" datatype="timestamp" description="操作时间"/>
            <attribute name="input_parameters" datatype="int" description="输入参数"/>
            <attribute name="result" datatype="int" description="结果"/>
            <attribute name="result_message" datatype="int" description="处理结果"/>
            <attribute name="status" datatype="str" description="状态"/>
        </entity>
    </dataModel>
    <!-- 4.系统参数 - 描述运行本插件包需要的系统参数 -->
    <systemParameters>
        <systemParameter name="xxx" defaultValue='xxxx' scopeType="global"/>
        <systemParameter name="xxx" defaultValue='xxxx' scopeType="plugin-package"/>
    </systemParameters>

    <!-- 5.权限设定 -->
    <authorities>
        <authority systemRoleName="admin">
            <menu code="JOBS_SERVICE_CATALOG_MANAGEMENT"/>
            <menu code="JOBS_TASK_MANAGEMENT"/>
        </authority>
        <authority systemRoleName="wecube_operator">
            <menu code="JOBS_TASK_MANAGEMENT"/>
        </authority>
    </authorities>

    <!-- 6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等) -->
    <resourceDependencies>
        <docker imageName="service_management" containerName="service_management" portBindings="22000:21000"
                volumeBindings=""
                envVariables="-e DATA_SOURCE_URL={%s} -e DB_USER={%s} -e DB_PWD={%s} -e CORE_ADDR={%s}"/>
        <mysql schema="service_management" initFileName="init.sql" upgradeFileName="upgrade.sql"/>
        <s3 bucketName="service_management"/>
    </resourceDependencies>

    <!-- 7.插件列表 - 描述插件包中单个插件的输入和输出 -->
    <plugins>
        <plugin name="task" package="service-management" entity="task">
            <interface action="create" path="/service-management/tasks" httpMethod='POST'>
                <inputParameters>
                    <parameter datatype="string" mappingType='system_variable' mappingSystemVariableName='1' required='Y'>
                        callbackUrl
                    </parameter>
                    <parameter datatype="string" mappingType='context' required='N'>description</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>name</parameter>
                    <parameter datatype="string" mappingType='entity' mappingEntityExpression='name_xxx' required='Y'>
                        operatorRoleId
                    </parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>processDefinitionKey</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>processInstanceId</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>reporter</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>serviceRequestId</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">status</parameter>
                    <parameter datatype="string">message</parameter>
                </outputParameters>
            </interface>
        </plugin>
        <plugin name="service_request" entity="service_request">
            <interface action="update" path="/service-management/service-requests/{service-request-id}/done"
                       httpMethod='PUT'>
                <inputParameters>
                    <parameter datatype="string" mappingType='system_variable' mappingSystemVariableName='1' required='Y'>
                        service-request-id
                    </parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>result</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">status</parameter>
                    <parameter datatype="string">message</parameter>
                </outputParameters>
            </interface>
        </plugin>
    </plugins>
</package>

=== WeBankPartners/wecube-platform/platform-core/src/test/resources/plugin/sample-plugin-config-without-data-model-entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="service-management" version="v0.1"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plugin-config-v2.xsd">

    <!-- 1.析 - 描述运行本插件包需要的其他插件包 -->
    <packageDependencies>
        <packageDependency name='xxx' version='1.0'/>
        <packageDependency name='xxx233' version='1.5'/>
    </packageDependencies>

    <!-- 2.菜单注入 - 描述运行本插件包需要注入的菜单 -->
    <menus>
        <menu code='JOBS_SERVICE_CATALOG_MANAGEMENT' cat='JOBS' displayName="Servive Catalog Management">/service-catalog</menu>
        <menu code='JOBS_TASK_MANAGEMENT' cat='JOBS' displayName="Task Management">/task-management</menu>
    </menus>

    <!-- 3.数据模型 - 描述本插件包的数据模型,并且描述和Framework数据模型的关系 -->
    <dataModel isDynamic="false">
    </dataModel>

    <!-- 4.系统参数 - 描述运行本插件包需要的系统参数 -->
    <systemParameters>
        <systemParameter name="xxx" defaultValue='xxxx' scopeType='global'/>
        <systemParameter name="xxx" defaultValue='xxxx' scopeType='plugin-package'/>
    </systemParameters>

    <!-- 5.权限设定 -->
    <authorities>
        <authority systemRoleName="admin" >
            <menu code="JOBS_SERVICE_CATALOG_MANAGEMENT" />
            <menu code="JOBS_TASK_MANAGEMENT" />
        </authority >
        <authority systemRoleName="wecube_operator" >
            <menu code="JOBS_TASK_MANAGEMENT" />
        </authority >
    </authorities>

    <!-- 6.运行资源 - 描述部署运行本插件包需要的基础资源(如主机、虚拟机、容器、数据库等) -->
    <resourceDependencies>
        <docker imageName="service_management" containerName="service_management" portBindings="22000:21000" volumeBindings="" envVariables="-e DATA_SOURCE_URL={%s} -e DB_USER={%s} -e DB_PWD={%s} -e CORE_ADDR={%s}"/>
        <mysql schema="service_management" initFileName="init.sql" upgradeFileName="upgrade.sql"/>
        <s3 bucketName="service_management"/>
    </resourceDependencies>

    <!-- 7.插件列表 - 描述插件包中单个插件的输入和输出 -->
    <plugins>
        <plugin name="task">
            <interface action="create" path="/service-management/tasks" httpMethod='POST'>
                <inputParameters>
                    <parameter datatype="string" mappingType='system_variable' mappingSystemVariableId='1' required='Y'>callbackUrl</parameter>
                    <parameter datatype="string" mappingType='context'  required='N'>description</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>name</parameter>
                    <parameter datatype="string" mappingType='entity' mappingEntityExpression='name_xxx' required='Y'>operatorRoleId</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>processDefinitionKey</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>processInstanceId</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>reporter</parameter>
                    <parameter datatype="string" mappingType='context' required='Y'>serviceRequestId</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">status</parameter>
                    <parameter datatype="string">message</parameter>
                </outputParameters>
            </interface>
        </plugin>
        <plugin name="service request management">
            <interface action="update" path="/service-management/service-requests/{service-request-id}/done" httpMethod='PUT'>
                <inputParameters>
                    <parameter datatype="string" mappingType='system_variable' mappingSystemVariableId='1' required='Y'>service-request-id</parameter>
                    <parameter datatype="string" mappingType='context'  required='Y'>result</parameter>
                </inputParameters>
                <outputParameters>
                    <parameter datatype="string">status</parameter>
                    <parameter datatype="string">message</parameter>
                </outputParameters>
            </interface>
        </plugin>
    </plugins>
</package>
